### ISSUE TITLE
VERCEL DJANGO 404 NOT FOUND

### ISSUE THREAD

**Issue by bobwatcherx** [jayhale/vercel-django-example#4]
i create my Django Hello App
and i follow your Code  and RUN SERVER LOCAL IS SUCCESS NO ERROR

and Deploy TO VERCEL  . but i have 404 NOT FOUND 

my example code 
https://github.com/bobwatcherx/verceldjangoerror.git

**Comment by jayhale** [comment]
@bobwatcherx, could you provide your Vercel logs and a debug-enabled public url for the project?
